"""create courses table

Revision ID: 77523cd7dbe6
Revises: dbe9a96096b7
Create Date: 2024-06-28 09:17:54.983530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77523cd7dbe6'
down_revision = 'dbe9a96096b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('duration', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    # ### end Alembic commands ###
